server:
  port: 8082

spring:
  application:
    name: WALLET-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka